server.port=8082
spring.threads.virtual.enabled=true
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ms-reporting_db}
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ms-reporting_db}
spring.data.mongodb.database=ms-reporting_db
spring.mongodb.database=ms-reporting_db